service: default
runtime: go111
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
# domain verify for sinmetal
- url: /googlee8b3bb4ba6763838.html
  static_files: googlee8b3bb4ba6763838.html
  upload: googlee8b3bb4ba6763838.html
- url: /swagger-ui
  static_dir: swagger-ui
  login: admin
- url: /ocn/.*
  script: auto
- url: /_ah/push-handlers/.*
  script: auto
  login: admin
- url: /.*
  script: auto
  login: admin